// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoxVcaUa6rVOBymgD_RQ7gTE0uz1zHUcI',
    appId: '1:199954355172:web:33b4f5486b494b1decedf1',
    messagingSenderId: '199954355172',
    projectId: 'tdee-adaptive-app',
    authDomain: 'tdee-adaptive-app.firebaseapp.com',
    storageBucket: 'tdee-adaptive-app.firebasestorage.app',
    measurementId: 'G-0YDFXBKHT1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDygXjHXNMsrQ-bUqnK56BjYkeKaJx9zzs',
    appId: '1:199954355172:android:4e0dcf603ff57c98ecedf1',
    messagingSenderId: '199954355172',
    projectId: 'tdee-adaptive-app',
    storageBucket: 'tdee-adaptive-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIRL5sUBKR3JXj0ObvbTvHPWtRV8gefaY',
    appId: '1:199954355172:ios:eeabb34b6a7d98baecedf1',
    messagingSenderId: '199954355172',
    projectId: 'tdee-adaptive-app',
    storageBucket: 'tdee-adaptive-app.firebasestorage.app',
    iosBundleId: 'com.tdeeapp.client',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIRL5sUBKR3JXj0ObvbTvHPWtRV8gefaY',
    appId: '1:199954355172:ios:eeabb34b6a7d98baecedf1',
    messagingSenderId: '199954355172',
    projectId: 'tdee-adaptive-app',
    storageBucket: 'tdee-adaptive-app.firebasestorage.app',
    iosBundleId: 'com.tdeeapp.client',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoxVcaUa6rVOBymgD_RQ7gTE0uz1zHUcI',
    appId: '1:199954355172:web:10342e490ed82954ecedf1',
    messagingSenderId: '199954355172',
    projectId: 'tdee-adaptive-app',
    authDomain: 'tdee-adaptive-app.firebaseapp.com',
    storageBucket: 'tdee-adaptive-app.firebasestorage.app',
    measurementId: 'G-729HYZYRGF',
  );
}
